name: build-and-push-docker-images-gitleaks

on:
  push:
    branches:
      - "main"
    paths:
      - 'gitleaks/**'

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/docker-image-reusable.yml
    with:
      imagename: gitleaks
    secrets: inherit
