name: build-and-push-docker-images-zap-proxy

on:
  push:
    branches:
      - "main"
    paths:
      - 'zap/**'

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/docker-image-reusable.yml
    with:
      imagename: zap
    secrets: inherit
