name: build-and-push-docker-images-semgrep

on:
  push:
    branches:
      - "main"
    paths:
      - 'semgrep/**'

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/docker-image-reusable.yml
    with:
      imagename: semgrep
    secrets: inherit
