name: build-and-push-docker-images-trivy

on:
  push:
    branches:
      - "main"
    paths:
      - 'trivy/**'

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/docker-image-reusable.yml
    with:
      imagename: trivy
    secrets: inherit
